### ISSUE TITLE
Sign In With Microsoft

### ISSUE THREAD

**Issue by DarranMullen** [dmjones/flutter_auth_buttons#1]
Button for Windows Sign In as per;

https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-branding-in-azure-ad-apps

**Comment by dmjones** [comment]
Good suggestion. Microsoft provides decent guidance in that document you linked to.

Pull requests welcome.

**Comment by dmjones** [comment]
Added in v0.5.0.
