### ISSUE TITLE
Icon doesn't work on google button

### ISSUE THREAD

**Issue by UglyBob79** [dmjones/flutter_auth_buttons#10]
I just tried version 0.5.0 in my project with a google button (dark) and I get no icon and this exception:

I/flutter (24157): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (24157): The following assertion was thrown resolving an image codec:
I/flutter (24157): Unable to load asset: packages/flutter_auth_buttons/graphics/google-logo.png
I/flutter (24157): 
I/flutter (24157): When the exception was thrown, this was the stack:
I/flutter (24157): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (24157): <asynchronous suspension>
I/flutter (24157): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:464:44)
I/flutter (24157): <asynchronous suspension>
I/flutter (24157): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:449:14)
I/flutter (24157): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:315:48)
I/flutter (24157): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
I/flutter (24157): #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:315:25)
I/flutter (24157): (elided 13 frames from package dart:async)
I/flutter (24157): 
I/flutter (24157): Image provider: AssetImage(bundle: null, name:
I/flutter (24157):   "packages/flutter_auth_buttons/graphics/google-logo.png")
I/flutter (24157): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#833bd(), name:
I/flutter (24157):   "packages/flutter_auth_buttons/graphics/google-logo.png", scale: 1.0)
I/flutter (24157): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by UglyBob79** [comment]
Tested 0.4.0 now and there it works fine...

**Comment by dmjones** [comment]
That's an odd one. I can't reproduce at my end.

Also, if you look at the [differences between 0.4.0 and 0.5.0](https://github.com/dmjones/flutter_auth_buttons/compare/v0.4.0...v0.5.0), there is nothing related to the Google button.

Have you tried a `flutter clean` to trigger a fresh build?

**Comment by UglyBob79** [comment]
Well, you are right, I changed back to 0.5.0 now, the issue is gone. So I will close my issue.
