### ISSUE TITLE
How do you get the rounded button

### ISSUE THREAD

**Issue by premtemp1** [dmjones/flutter_auth_buttons#11]
Is there an option to get a rounded button with the logo icon. e.g  for facebook , a round circle with the "f" inside ...

**Comment by dmjones** [comment]
You can control the border-radius of the buttons, see the README for example code. But the buttons are designed to be used with text, so there is no way to get a simple round button with a logo inside.

The Facebook brand guidelines suggest using text: https://developers.facebook.com/docs/facebook-login/userexperience#buttondesign

**Comment by dmjones** [comment]
Please reopen if I haven't answered your question.
