### ISSUE TITLE
Apple Sign in Button

### ISSUE THREAD

**Issue by OliverNarramore** [dmjones/flutter_auth_buttons#12]
Will the apple sign in button be supported in future updates? https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/

**Comment by dmjones** [comment]
Pull requests very welcome. It looks like they provide adequate guidance to style the button.

**Comment by json469** [comment]
I would be interested in working on this one if no one is?

**Comment by dmjones** [comment]
Go for it! Thanks.

**Comment by json469** [comment]
👍 https://github.com/dmjones/flutter_auth_buttons/pull/13

**Comment by dmjones** [comment]
This has been merged, available in v0.6.0.
