### ISSUE TITLE
Inconsistent fonts

### ISSUE THREAD

**Issue by stargazing-dino** [dmjones/flutter_auth_buttons#16]
Hi!

The GoogleSignInButton specifies a Roboto font but the Facebook one defaults to application font style. I have a stylized font for my overall app but I'd like to have the auth buttons consistently Roboto.

I tried to overwrite the font family in the FacebookSignInButton by doing:

```dart
DefaultTextStyle(
  style: TextStyle(fontFamily: 'Roboto'),
  child: FacebookSignInButton(
    onPressed: () => handlePress(auth, auth.facebookSignIn),
  ),
);
```

But I still end up getting 

![auth_buttons](https://user-images.githubusercontent.com/29642168/66720046-bb132100-edb4-11e9-9eea-b559171348af.PNG)

**Comment by dmjones** [comment]
The Facebook button defines a text style, which means your `DefaultTextStyle` is ignored:

```dart
// facebook.dart...

          child: Text(
            text,
            style: TextStyle(
              // default to the application font-style
              fontSize: 18.0,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
        ),
```

I think the right approach here is another optional parameter, for all buttons, to allow callers to set a preferred text style. I'll try and find time to look into that. PRs also welcome.
