### ISSUE TITLE
Google login button looks slightly off

### ISSUE THREAD

**Issue by dolanmiu** [dmjones/flutter_auth_buttons#22]
Official guidelines:

https://developers.google.com/identity/branding-guidelines

![image](https://user-images.githubusercontent.com/2917613/74888399-be777400-5375-11ea-9d65-d5def549b74c.png)

`flutter_auth_buttons`:

![image](https://user-images.githubusercontent.com/2917613/74888390-b6b7cf80-5375-11ea-9abd-a53e16f9478a.png)

There is a difference. I think it's the right padding which makes it look funny, and perhaps the font size too

**Comment by dmjones** [comment]
The Google design info is inconsistent. See the source comments:

https://github.com/dmjones/flutter_auth_buttons/blob/master/lib/src/google.dart#L44

I struggled to get it perfect. PRs welcome if you can improve it.
