### ISSUE TITLE
icon position is different

### ISSUE THREAD

**Issue by shinriyo** [dmjones/flutter_auth_buttons#40]
icon position is different from them?
or, is it official position?

<img width="396" alt="Screen Shot 2020-09-04 at 8 11 47" src="https://user-images.githubusercontent.com/396927/92182350-77bb1880-ee86-11ea-9b8d-3f73baf8a471.png">

Or, Can I use `textAlign: TextAlign.center,`?

**Comment by dmjones** [comment]
That's the official position of the icons.

If you updated to 0.10.0 (which was released about 5 minutes ago), you can use `centred: true`. See the bottom of the README file for an example.

**Comment by shinriyo** [comment]
Thank you.
It is released.
I will try.

https://pub.dev/packages/flutter_auth_buttons/versions
