### ISSUE TITLE
Images on buttons load in with a delay

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dmjones/flutter_auth_buttons#8]
Can you precache the images in the initstate?
https://stackoverflow.com/a/51343954/2880055

**Comment by dmjones** [comment]
Sounds like a good idea. PRs welcome :-)

**Comment by hjJunior** [comment]
I think I can do it, sure, If there isn't anybody working on it...
What do u'all think about it?

**Comment by ThinkDigitalSoftware** [comment]
I moved on, so feel free :)

**Comment by bitmoxy** [comment]
@ThinkDigitalSoftware - I was looking into this issue to possibly create a PR. I can't seem to duplicate it. I tested on both iPhone and Android emulators as well as the physical device itself but have seen no delay in images displaying. Can you provide more information?

**Comment by ThinkDigitalSoftware** [comment]
It's been a while, since I've used the package,
